# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=200)),
                ('image', stdimage.models.StdImageField(upload_to='%Y/%m/%d/')),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('brand_name', models.CharField(max_length=20)),
            ],
        ),
    ]
