# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('L', 'Laptop'), ('D', 'Desktop')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
